### PR TITLE
Added alpha Availability Endpoint

### PR DESCRIPTION
**Pull request by adenta**
I added the availability endpoint so other people can use it.

### CODE REVIEW

**Comment by Haziba** [comment]
Thanks for this, I've added these changes to our main repository :)

**Comment by adenta** [comment]
Did you test this?

**Comment by stephenbinns** [comment]
Hi @adenta are you encountering issues?

**Comment by adenta** [comment]
Yes. I emailed somebody from your support team. For some reason my object
arrays are being compressed into strings when I target this endpoint.

**Comment by stephenbinns** [comment]
I see I believe the current version should resolve those issues, can you try after updating the package?

**Comment by adenta** [comment]
Real sorry, but the npm package is at 1.2. How can I use this new updated version we just merged in?

**Comment by gshutler** [comment]
@adenta 1.3.0 has now been released.

**Pull request closed without merging**
